### ISSUE TITLE
modporter rails plugin does not work with paperclip

### ISSUE THREAD

**Issue by bdmac** [actionrails/modporter#1]
The modporter rails plugin gives errors in Paperclip because they expect either the standard File object that is normally received or a Paperclip::Attachment object, not a ModPorter::UploadedFile object.  

Specifically in their Attachment::assign method they try to call uploaded_file.to_tempfile() on the received uploaded_file object which was failing on the ModPorter::UploadedFile object.  I realize Paperclip is not the place to fix this but since they already do something similar for Paperclip::Attachment objects I was able to quickly get around it by doing this in their assign method:

if uploaded_file.is_a?(ModPorter::UploadedFile)
        uploaded_file = File.new(uploaded_file.path)
end

**Comment by lifo** [comment]
Thanks for the report. Ideally modporter rails plugin should make this transparent. So if you want to submit a patch to change the current ModPorter::UploadedFile implementation, that'll be great!

Thanks.

**Comment by saizai** [comment]
Couldn't this be fixed by making ModPorter's return a subclass of File itself, and support all its methods (eg #to_tempfile)?

**Comment by millisami** [comment]
Hey, is this issue with paperclip resolved? My app uses Paperclip heavily, so before giving it a try, I wanna be sure that it works with paperclip?

**Comment by millisami** [comment]
Well, I couldn't wait long and gave it a try. But the same problem persisted with the paperclip one.
Ain't this gonna be fixed soon???
I really liked it coz my app uses the file-uploads heavily and I'm sure this mod_porter will optimize my app performance!!
Need this fixed soon.

**Comment by lifo** [comment]
I have applied all the pending patches. Could you please submit a patch to fix the issue ?

Thanks.

**Comment by millisami** [comment]
I think we need ask bdmac to submit the patch.

**Comment by NZKoz** [comment]
We've applied his changes.

**Comment by millisami** [comment]
Does that mean now its working with Paperclip??

**Comment by NZKoz** [comment]
Yes, it works fine

**Comment by millisami** [comment]
ok, I'll try it again and get back.
